-- TODO: Get this to create the menu with both options <23-04-23> --
--vim.g.vimwiki_list = {
  --{},
  --{
    --name = 'phd',
    --path = '~/Documents/Research/PhD/Kelvin-s-PhD-wiki',
    --path_html = '~/Documents/Research/PhD/Kelvin-s-PhD-wiki/html',
    --template_path = '~/Documents/Research/PhD/Kelvin-s-PhD-wiki/templates/',
  --}
--}
